---
title: "Brown bag seminars"
date: 2024-07-11

abstract: ""

number-sections: true
  
keywords: ""
  
format:
  html:
    code-fold: true
    toc: true
    toc-depth: 6
    html-math-method: katex
    css: styles.css
    
execute:
  warning: false
  message: false

---

# Information {#sec-info}

"Brown bag" is a series of seminars focused on agriculture, food, and economics in low and middle income settings.

The name originates from the paper bag children used to bring to school with lunch inside. It suggests that the seminar takes place at lunch time, when audience is invited to bring their food and have lunch while listening to the speaker.

# Rules {#sec-rules}

1. Each seminar lasts 1 hour and starts at noon.
2. Bring your lunch and consume it quietly, respecting the speaker.
3. The seminar is discussion focused, we give enough time for questions, answers, and discussion on the topic. When you prepare a presentation, do not overload it with information or slides - leave room for everyone to ask questions and talk.

# Upcoming seminars {#sec-upcoming}

- 2024 Sep 12
- 2024 Oct 03
- 2024 Nov 07
- 2024 Dec 05

# Past seminars {#sec-past}

| Date | Presenter | Title | Affiliation | Location |
|-|-|-|-|-|
| 2024 Jul 04 | Christian Grovermann | Evidence for agroecological intensification ([link](https://github.com/Global-Health-Engineering/brown-bag/blob/main/presentations/2024-07-04-evidence-for-agroecological-intensification.pdf)) | [FiBL](https://www.fibl.org/en/)| SOL B 4 |
| 2024 Jun 06 | Philipa Birago Akuoko | Governing informality in public spaces and its implication for food supply ([link](https://github.com/Global-Health-Engineering/brown-bag/blob/main/presentations/2024-06-06-informality-public-space-and-food-supply.pdf)) | [University of Bern](https://www.geography.unibe.ch/about_us/the_institute/index_eng.html) | SOL B 4  |
| 2024 May 02 | Celestina Heepen | Qualitative investigation of labour matching processes in the Swiss vine production | FSEP  | SOL B 4 |
| 2024 Apr 04 | Rebecca Alcock | Topic: Rural health facility electrification with off-grid solar and micromobility networks | [University of Wisconsin-Madison](https://ghi.wisc.edu/) | CLD D 1 |
| 2024 Mar 07 | Marie Sigrist | I have no choice, I have to pick this coffee to cope! Power asymmetries and strategies in the coffee sector in South of Minas Gerais, Brazil | AET | SOL B 4 |
| 2024 Feb 01 | Moritz Egger | Uncovering sustainability perspectives: Exploring local definitions and criteria in cocoa, olive, and almond farming communities through a Photovoice action research process | AET-FIBL | SOL B 4 |
| 2024 Jan 18 | Giorgia Giordani | NA | [University of Tuscia](https://www.unitus.it/en/) | SOL B 4 |
| 2023 Dec 09 | Lin Boynton | Recap from INC-3: The United Nations negotiations for the Global Plastics Treaty | GHE | CLD D 1 |
| 2022 Nov 11)| Mollie Chapman | Redesigning Direct Payments to Farmers in Switzerland | TdLab | CLD D 1 |

# Participating ETH groups

1. [The Agroecological Transitions Group (AET)](https://agroecological-transitions.ethz.ch/)
2. [Food System Economics and Policy Group (FSEP)](https://fsep.ethz.ch/)
3. [Global Health Engineering (GHE)](https://ghe.ethz.ch/)
4. [Natural Resource Policy Group (NARP)](https://narp.ethz.ch/en/)
5. [Transdisciplinarity Lab (TdLab)](https://tdlab.usys.ethz.ch/)
